### ISSUE TITLE
speedgains with a less verbose conversion 

### ISSUE THREAD

**Issue by twobombs** [LeventErkok/crackNum#5]
Thanks for creating the most awesome number converter on the planet. It has helped immensely as I need to convert a lot of binary/hex-/decimal values to their respective hex layout. It is faster then Python and gives all sorts of interesting details as output.

And therein lies the rub: would crackNum be faster when less verbose, skipping other calculations ? Asking because I am converting more and more data and at some piont it might take weeks to convert the data on a dedicated rig. All I need is the hexdecimal layout.

Might not be a big win but I thought it might not hurt to ask. [Project's Git](https://github.com/twobombs/qracknet)

![Screenshot from 2021-11-06 12-01-39](https://user-images.githubusercontent.com/12692227/140607273-9c51ff05-ab34-4fa7-b0cf-81cb540efdb3.png)

**Comment by LeventErkok** [comment]
CrackNum isn't really designed for speed; or for such bulk conversions. This is because it supports all sorts of floating-point formats (i.e., with varying exponent and significand bits) and thus the conversion is done via a complicated process to support all these formats. Turning of verbosity wouldn't really save anything, as the bulk of the time is spent elsewhere.

But if all you're trying to do is to convert a float to its hex-layout, then you should simply use a much simpler program to do so, instead of going through CrackNum. It could be as simple as this:

```haskell
import Data.Char
import Data.ReinterpretCast
import Numeric

floatToHex :: Float -> String
floatToHex f = chunk $ map toUpper $ showHex (floatToWord f) ""
 where chunk "" = ""
       chunk xs = let (f, s) = splitAt 4 xs in f ++ ' ' : chunk s
```

An example use:

```
*Main> putStrLn $ floatToHex 123456789
4CEB 79A3
```

I'd expect this to run significantly faster than crackNum, allowing you to do bulk processing.

**Comment by twobombs** [comment]
Thank you for the feedback, will look into it ! :)

**Comment by LeventErkok** [comment]
I can potentially add a bulk-convert option to CrackNum for single and double-precision only, which bypasses the heavy part. Though I still think a separate program is best for this purpose. Let me know if that's not possible for you for whatever reason.

**Comment by twobombs** [comment]
> I can potentially add a bulk-convert option to CrackNum for single and double-precision only, which bypasses the heavy part. Though I still think a separate program is best for this purpose. Let me know if that's not possible for you for whatever reason.

A separate program or high-level language, for me, would not be my first choice as the special sauce that is crackNum sets it apart from those two other options. In that line of thought a bulk integration would IMHO be a fine addition for crackNum, less verbose but integrated even at the costs of being less speedily then a separate stand alone program but with less overhead then a high level language solution such as Python.

**Comment by LeventErkok** [comment]
In that case I'd suggest do a separate program for bulk converts and use crackNum for when you want finer level of detail. It'll be as simple as putting the function I posted above in a file and compiling. (You can add a version that does the double-precision as well.) It's best to keep the two separate I think, and you can pick whichever you want.
